//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.0.
//


package com.fei_ke.chiphellclient.ui.customviews;

import android.content.Context;
import android.widget.ImageView;
import android.widget.TextView;
import com.fei_ke.chiphellclient.R.id;
import com.fei_ke.chiphellclient.R.layout;
import org.androidannotations.api.view.HasViews;
import org.androidannotations.api.view.OnViewChangedListener;
import org.androidannotations.api.view.OnViewChangedNotifier;


/**
 * We use @SuppressWarning here because our java code
 * generator doesn't know that there is no need
 * to import OnXXXListeners from View as we already
 * are in a View.
 * 
 */
@SuppressWarnings("unused")
public final class ThreadItemView_
    extends ThreadItemView
    implements HasViews, OnViewChangedListener
{

    private boolean alreadyInflated_ = false;
    private final OnViewChangedNotifier onViewChangedNotifier_ = new OnViewChangedNotifier();

    public ThreadItemView_(Context context) {
        super(context);
        init_();
    }

    public static ThreadItemView build(Context context) {
        ThreadItemView_ instance = new ThreadItemView_(context);
        instance.onFinishInflate();
        return instance;
    }

    /**
     * The mAlreadyInflated_ hack is needed because of an Android bug
     * which leads to infinite calls of onFinishInflate()
     * when inflating a layout with a parent and using
     * the <merge /> tag.
     * 
     */
    @Override
    public void onFinishInflate() {
        if (!alreadyInflated_) {
            alreadyInflated_ = true;
            inflate(getContext(), layout.layout_thread_item, this);
            onViewChangedNotifier_.notifyViewChanged(this);
        }
        super.onFinishInflate();
    }

    private void init_() {
        OnViewChangedNotifier previousNotifier = OnViewChangedNotifier.replaceNotifier(onViewChangedNotifier_);
        OnViewChangedNotifier.registerOnViewChangedListener(this);
        OnViewChangedNotifier.replaceNotifier(previousNotifier);
    }

    @Override
    public void onViewChanged(HasViews hasViews) {
        textViewDate = ((TextView) hasViews.findViewById(id.textView_date));
        textViewCount = ((TextView) hasViews.findViewById(id.textView_count));
        imageViewIcon = ((ImageView) hasViews.findViewById(id.imageView_icon));
        textViewTitle = ((TextView) hasViews.findViewById(id.textView_title));
        textViewBy = ((TextView) hasViews.findViewById(id.textView_by));
    }

}
